name: Run Python Scripts and Save CSV

on:
  schedule:
    - cron: '05 5 * * *'  # Set waktu sesuai UTC
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    - name: Run request.py
      run: |
        python request.py

    - name: Run ekstrak.py
      run: |
        python ekstrak.py

    - name: Run scrapping_bpn.py
      run: |
        python scrapping_bpn.py
    - name: Run sql.py
      run: |
        python sql.py
    - name: Run convert_to_json.py
      run: |
        python convert_to_json.py

    - name: Pull changes from remote before pushing
      run: |
        git pull origin main

    - name: Commit and Push CSV
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -f medium_cikurubuk.csv medium_pancasila.csv premium_cikurubuk.csv premium_pancasila.csv data_gabungan_dengan_rata2.csv processed_beras_prices.csv data_harga.db data_harga.json
        git commit -m "Update CSV data [$(date +'%Y-%m-%d %H:%M:%S')]" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
