name: Run Notebook and Save CSV

on:
  schedule:
    - cron: '26 10 * * *'  # 10:10 UTC = 17:10 WIB
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests papermill jupyter ipykernel

    - name: Install Jupyter kernel
      run: |
        python -m ipykernel install --user

    - name: Check available kernels
      run: |
        jupyter kernelspec list

    - name: Run the notebook
      run: |
        papermill code.ipynb output.ipynb -k python3

    - name: Commit and Push CSV
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add *.csv
        git commit -m "Update CSV data [$(date +'%Y-%m-%d %H:%M:%S')]" || echo "No changes to commit"
        git push
